### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by tbongiorno1** [tbongiorno1/GOTquiz#1]
Hi Andrew,

I am working on the instance of my project that was pushed this morning.

I am running into a weird problem that myself, Kate, google, and other class mates were not able to resolve.

located inside of my app.js folder you will find the code for creating new question windows for my game. For some strange reason the first and third window are working fine but the middle (second) window has two click events being added. since they were all identical I went and changed the content of the three windows and it seems that the second window is being created twice.

I have tried using: google, JQuery(.once,.unbind), kate, and other classmates.

![screen shot 2016-09-01 at 11 47 39 am](https://cloud.githubusercontent.com/assets/20803252/18174017/e9a63a12-7039-11e6-8cc8-91cf3d94555b.png)
![screen shot 2016-09-01 at 11 48 00 am](https://cloud.githubusercontent.com/assets/20803252/18174025/f2f32648-7039-11e6-8383-4561a4894ca4.png)

**Comment by amadden80** [comment]
How exactly do I recreate the problem?  
I've opened your application, I click on each answer, I see the 'clicked' is logged once per click.  This true for all the questions

**Comment by amadden80** [comment]
After your `questionThird` is created, which question are you rendering?

**Comment by amadden80** [comment]
Has this issue been resolved?

**Comment by amadden80** [comment]
If it is resolved, please close this issue.
